/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Connection.Coneccion;
import Entity.Clientes;
import Entity.Comunicador;
import Entity.ItemVen;
import Entity.MyIcon;
import Entity.Productos;
import Entity.Usuario;
import Entity.Venta;
import java.awt.Frame;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperPrintManager;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;

/**
 *
 * @author Melanio
 */
public class AnularVentas extends javax.swing.JInternalFrame {

    /**
     * Creates new form Ventas
     */
    DefaultTableModel modelo;
    Productos pro = new Productos();
    TableRowSorter<TableModel> sorter;
    DecimalFormat df = new DecimalFormat("###,###,###.##");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    Clientes clie = new Clientes();
    public Usuario usu = (Usuario) Comunicador.getObjeto();
    
    Calendar Cfecha = new GregorianCalendar();
    String fecha = "";
    
    double Saldo = 0.0;
    double Entrega = 0.0;
    URL archi;
    Coneccion coneccion;
    Connection con;
    Statement stmt;
    
    public static ver_total vt;
    private Frame ven;
    
    int codvent = 0;
    int tipfac = 1;
    
    public AnularVentas() {
        initComponents();
        TableModel();
        usuario();
        
        jlDeuda.setVisible(false);
        jtxMonDeu.setVisible(false);
        jRBCredito.setVisible(false);
        jRBContado.setVisible(false);
        txFecha.setText(sdf.format(Cfecha.getTime()));
    }
    
    private void conectar() {
        try {
            coneccion = new Coneccion();
            con = coneccion.getCon();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, closable);
        }
    }
    
    private void usuario() {
        if (usu.getAcc_id() != null) {
            txCodUsu.setText(usu.getAcc_id().toString());
            txDesusu.setText(usu.getAcc_nombre());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bGTipos = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVentas = new javax.swing.JTable();
        txTotal = new javax.swing.JTextField();
        txCodCli = new javax.swing.JTextField();
        txDesCli = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jlDeuda = new javax.swing.JLabel();
        jRBContado = new javax.swing.JRadioButton();
        jRBCredito = new javax.swing.JRadioButton();
        jtxMonDeu = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txMotivo = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        txCodUsu = new javax.swing.JTextField();
        txDesusu = new javax.swing.JTextField();
        btCancel = new javax.swing.JButton();
        txFecha = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txNumVen = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Anular Ventas");
        getContentPane().setLayout(null);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TablaVentas.setBackground(new java.awt.Color(252, 252, 185));
        TablaVentas.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        TablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "DESCRIPCION", "CANTIDAD", "PRECIO", "TOTAL", "FECHA", "HORA"
            }
        ));
        TablaVentas.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        TablaVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        TablaVentas.setEnabled(false);
        TablaVentas.setRowHeight(20);
        TablaVentas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TablaVentasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(TablaVentas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 680, 180));

        txTotal.setEditable(false);
        txTotal.setBackground(new java.awt.Color(0, 102, 0));
        txTotal.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        txTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txTotal.setFocusable(false);
        jPanel1.add(txTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 200, 40));

        txCodCli.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txCodCli.setEnabled(false);
        txCodCli.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txCodCliFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txCodCliFocusLost(evt);
            }
        });
        txCodCli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCodCliKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txCodCliKeyTyped(evt);
            }
        });
        jPanel1.add(txCodCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 120, -1));

        txDesCli.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txDesCli.setEnabled(false);
        jPanel1.add(txDesCli, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 390, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 55, 110, 20));

        jlDeuda.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jlDeuda.setText("Deuda Cliente:");
        jPanel1.add(jlDeuda, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 0, -1, 20));

        bGTipos.add(jRBContado);
        jRBContado.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jRBContado.setSelected(true);
        jRBContado.setText("CONTADO");
        jPanel1.add(jRBContado, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 370, -1, -1));

        bGTipos.add(jRBCredito);
        jRBCredito.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jRBCredito.setText("CREDITO");
        jRBCredito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRBCreditoActionPerformed(evt);
            }
        });
        jPanel1.add(jRBCredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 370, -1, -1));

        jtxMonDeu.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jtxMonDeu.setEnabled(false);
        jtxMonDeu.setFocusable(false);
        jPanel1.add(jtxMonDeu, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 20, 140, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Cliente:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 20));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Motivo de Anulación:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, -1, -1));

        txMotivo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jPanel1.add(txMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 680, 30));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 90, 720, 340);

        saveButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        saveButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ico_delete.png"))); // NOI18N
        saveButton.setMnemonic('g');
        saveButton.setText("Anular");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(saveButton);
        saveButton.setBounds(210, 460, 130, 40);

        txCodUsu.setEnabled(false);
        getContentPane().add(txCodUsu);
        txCodUsu.setBounds(10, 0, 160, 28);

        txDesusu.setEnabled(false);
        getContentPane().add(txDesusu);
        txDesusu.setBounds(180, 0, 450, 28);

        btCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ico_cancel.png"))); // NOI18N
        btCancel.setMnemonic('c');
        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btCancel);
        btCancel.setBounds(390, 460, 140, 40);

        txFecha.setEditable(false);
        txFecha.setFocusable(false);
        getContentPane().add(txFecha);
        txFecha.setBounds(640, 0, 90, 28);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("F4-N° DEVENTA:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 50, 110, 20);

        txNumVen.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        txNumVen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txNumVenActionPerformed(evt);
            }
        });
        txNumVen.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txNumVenFocusLost(evt);
            }
        });
        txNumVen.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txNumVenKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txNumVenKeyTyped(evt);
            }
        });
        getContentPane().add(txNumVen);
        txNumVen.setBounds(130, 40, 160, 31);

        setBounds(0, 0, 757, 546);
    }// </editor-fold>//GEN-END:initComponents

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        if (!txNumVen.getText().isEmpty() && modelo.getRowCount() > 0) {
            if (!txMotivo.getText().isEmpty()) {
                anular();
            } else {
                JOptionPane.showMessageDialog(null, "Escriba motivo de anulación");
                txMotivo.grabFocus();
            }
            
        }
    }//GEN-LAST:event_saveButtonActionPerformed
    

    private void TablaVentasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TablaVentasKeyPressed

    }//GEN-LAST:event_TablaVentasKeyPressed

    private void txCodCliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCodCliKeyPressed

    }//GEN-LAST:event_txCodCliKeyPressed
    

    private void txCodCliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCodCliKeyTyped

    }//GEN-LAST:event_txCodCliKeyTyped

    private void txCodCliFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txCodCliFocusGained

    }//GEN-LAST:event_txCodCliFocusGained

    private void txCodCliFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txCodCliFocusLost

    }//GEN-LAST:event_txCodCliFocusLost

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        txNumVen.setText("");
        txNumVen.grabFocus();
        limpiar();
    }//GEN-LAST:event_btCancelActionPerformed

    private void jRBCreditoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRBCreditoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRBCreditoActionPerformed

    private void txNumVenKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNumVenKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (!txNumVen.getText().isEmpty()) {
                limpiar();
                consultarVenta();
            }
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_F4) {
                if (txNumVen.getText().isEmpty()) {
                    ver_numven vnum = new ver_numven(null, true);
                    vnum.setVisible(true);
                    Venta ven = vnum.vVent;
                    
                    if (ven != null) {
                        txNumVen.setText(ven.getVen_codigo().toString());
                    }
                }                
            }
        }
    }//GEN-LAST:event_txNumVenKeyPressed

    private void txNumVenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txNumVenKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9'))) {
            evt.consume();
        }
    }//GEN-LAST:event_txNumVenKeyTyped

    private void txNumVenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txNumVenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txNumVenActionPerformed

    private void txNumVenFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txNumVenFocusLost
        if (!txNumVen.getText().isEmpty()) {
            limpiar();
            consultarVenta();
        }

    }//GEN-LAST:event_txNumVenFocusLost
    
    private void consultarVenta() {
        try {
            Coneccion con = new Coneccion();
            ResultSet rs;
            String sql = "select ven_codigo,ven_fecha,ven_hora,ven_codven,acc_nombre,itv_codpro,pro_descri,pro_iva, "
                    + "itv_canti,itv_precio,ven_total,ven_cliente,case when cli_nombre is null then 'Ocacional' else  "
                    + "cli_nombre end,cli_ruc ,ven_tipo,ven_obs,(itv_canti*itv_precio) as stot, "
                    + "ven_numfac "
                    + "from ventas left join clientes cli on cli.cli_codigo = ventas.ven_cliente,item_ventas,productos,acceso "
                    + "where ven_situ=1 and pro_codigo=itv_codpro and ven_codigo=itv_codven "
                    + "and acc_id=ven_codven and ven_codigo=" + this.txNumVen.getText();
            con.consulta(sql);
            rs = con.getRs();
            while (rs.next()) {
                txCodCli.setText(String.valueOf(rs.getInt("ven_cliente")));
                txDesCli.setText(rs.getString("cli_nombre"));
                Object[] pro = new Object[modelo.getColumnCount()];
                pro[0] = rs.getInt("itv_codpro");
                pro[1] = rs.getString("pro_descri");
                pro[2] = df.format(rs.getDouble("itv_canti"));
                pro[3] = df.format(rs.getDouble("itv_precio"));
                
                double total = (rs.getDouble("itv_precio") * rs.getDouble("itv_canti"));
                pro[4] = df.format(total);
                pro[5] = sdf.format(rs.getDate("ven_fecha"));
                pro[6] = rs.getString("ven_hora");
                modelo.addRow(pro);
                txTotal.setText(df.format(rs.getDouble("ven_total")));
                
            }
            this.TablaVentas.setModel(modelo);
            con.close();
        } catch (Exception e) {
            
        }
        
    }
    
    private void anular() {
        try {
            coneccion = new Coneccion();
            con = coneccion.getCon();
            con.setAutoCommit(false);
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            
            stmt.executeUpdate("update ventas set ven_situ=0 where ven_codigo=" + txNumVen.getText());
            
            for (int i = 0; i < modelo.getRowCount(); i++) {
                stmt.executeUpdate("update productos set pro_cant= " + "(pro_cant + " + Double.parseDouble(TablaVentas.getValueAt(i, 2).toString()) + ") "
                        + "where pro_codigo=" + Integer.parseInt(TablaVentas.getValueAt(i, 0).toString()));
            }
            
            String Hora = new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime());
            Cfecha = Calendar.getInstance();
            fecha = sdf.format(Cfecha.getTime());
            int res;
            res = stmt.executeUpdate("insert into anuvent(avt_fecha,avt_hora,avt_codusu,avt_numven,avt_motivo) values('"
                    + sdf.parse(fecha) + "','" + Hora + "'," + usu.getAcc_id() + "," + txNumVen.getText() + ",'" + txMotivo.getText().trim() + "')");
            con.commit();
            if (res == 1) {
                JOptionPane.showMessageDialog(null, "Venta Anulada");
            }
            con.close();
            limpiar();
            txNumVen.setText("");
            
            txNumVen.grabFocus();
        } catch (SQLException | NumberFormatException e) {
            
        } catch (ParseException ex) {
            Logger.getLogger(AnularVentas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }
    
    private void TableModel() {
        modelo = (DefaultTableModel) TablaVentas.getModel();
        modelo.setRowCount(0);
        this.TablaVentas.setModel(modelo);
    }
    
    public void limpiar() {
        //txNumVen.setText("");
        txTotal.setText("");
        txCodCli.setText("");
        txDesCli.setText("");
        //txNumVen.grabFocus();
        modelo.setRowCount(0);
        TablaVentas.setModel(modelo);
        jlDeuda.setVisible(false);
        jtxMonDeu.setVisible(false);
        txMotivo.setText("");
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaVentas;
    private javax.swing.ButtonGroup bGTipos;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRBContado;
    private javax.swing.JRadioButton jRBCredito;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlDeuda;
    private javax.swing.JTextField jtxMonDeu;
    private javax.swing.JButton saveButton;
    private javax.swing.JTextField txCodCli;
    private javax.swing.JTextField txCodUsu;
    private javax.swing.JTextField txDesCli;
    private javax.swing.JTextField txDesusu;
    private javax.swing.JTextField txFecha;
    private javax.swing.JTextField txMotivo;
    private javax.swing.JTextField txNumVen;
    private javax.swing.JTextField txTotal;
    // End of variables declaration//GEN-END:variables
}
