/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Connection.Coneccion;
import Connection.con_acces;
import Entity.Clientes;
import Entity.Productos;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN7
 */
public class TranspasoAcces extends javax.swing.JFrame {

    /**
     * Creates new form TranspasoAcces
     */
    public TranspasoAcces() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Transpaso de datos");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setText("Productos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton2.setText("Marcas");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton3.setText("Sect / Rubro");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton4.setText("Clientes");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton5.setText("Actualizar Unidades");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5)
                    .addComponent(jButton4)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(322, 339));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int canti = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String sql = "";
         sql = "select IdeArt,EtqArt,CodBar,Codean13,TcoArt,CodArt,DesArt,RefArt,"
                    + "  UmeArt,MarArt," +
                        "DisArt,MinArt,ImpArt,Iv5Art,Iv1Art,CosArt,UtiArt,Pv1Art,Pv2Art,ExiArt,RubArt,Iv1Art from Articulo "
                    + "order by IdeArt";
        con_acces con = new con_acces();
        con.consulta(sql);
        ResultSet rs = null;
        rs = con.getRs();
        if (rs != null) {
            Coneccion co = new Coneccion();
            try {
                String sq = "";
                int codi = 0;
                String fecHor = "";
                co.update("TRUNCATE productos RESTART IDENTITY");
                while (rs.next()) {
                    
                    Productos producto = new Productos();
                    producto.setProCanmin(rs.getBigDecimal("MinArt"));
                    producto.setProCbarra(rs.getString("CodArt"));
                    String[] descri = rs.getString("DesArt").toUpperCase().trim().split("-");
                    String des="";
                    if(descri.length > 0 && descri != null){
                    for(int i=1;i<descri.length;i++){
                        des+=descri[i].trim();
                    }
                    }else{
                        System.out.println(rs.getString("DesArt"));
                        des=rs.getString("DesArt").toUpperCase().trim();
                    }
                    producto.setProDescri(des);
                    producto.setProCant(rs.getBigDecimal("ExiArt"));
                    producto.setProPre1(rs.getBigDecimal("CosArt"));
                    producto.setProPre3(rs.getBigDecimal("Pv1Art"));
                    producto.setProPre2(rs.getBigDecimal("Pv2Art"));
                    producto.setProUnidad(rs.getInt("UmeArt"));
                    producto.setProCate(rs.getInt("MarArt"));
                    producto.setProProvee(rs.getInt("DisArt"));
                    producto.setProSect(rs.getInt("RubArt"));
                    producto.setProIva(rs.getBigDecimal("Iv1Art"));
                    Calendar cal= new GregorianCalendar();
                     
                    producto.setProVenci(cal.getInstance().getTime());
                    
                    //System.out.println(producto.toString());
                    
                    sql = "Insert into productos(pro_descri,pro_pre1,pro_pre2,pro_pre3,"
                    + "pro_cant,pro_provee,pro_cate,pro_sect,pro_canmin,pro_venci,pro_cbarra,pro_unidad) "
                    + "values('" + producto.getProDescri() + "'," + producto.getProPre1() + ","
                    + producto.getProPre2() + "," + producto.getProPre3() + "," + producto.getProCant() + ","
                    + producto.getProProvee() + "," + producto.getProCate() + "," + producto.getProSect() + ","
                    + producto.getProCanmin() + ",'" + sdf.format(producto.getProVenci()) + "','" + producto.getProCbarra()+"'," 
                    + producto.getProUnidad()+")";
                    co.update(sql);
                    //System.out.println(producto.toString());
                    canti++;
                }
                JOptionPane.showMessageDialog(null, canti + " Productos Importados");
                co.close();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
        con.close();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       int canti = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String sql = "";
        sql = "select DesMar from AuxMarca";
        con_acces con = new con_acces();
        con.consulta(sql);
        ResultSet rs = null;
        rs = con.getRs();
        if (rs != null) {
            Coneccion co = new Coneccion();
            try {
                String sq = "";
                int codi = 0;
                String fecHor = "";
                co.update("TRUNCATE categoria RESTART IDENTITY");
                while (rs.next()) {
                    
                     sql = "INSERT INTO categoria(cate_descri) values('"+rs.getString(1)+"')";
                    

                    co.update(sql);
                    //System.out.println(producto.toString());
                    canti++;
                }
                JOptionPane.showMessageDialog(null, canti + " Marcas Importados");
                co.close();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
        con.close();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int canti = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String sql = "";
        sql = "select DesRub from AuxRubro";
        con_acces con = new con_acces();
        con.consulta(sql);
        ResultSet rs = null;
        rs = con.getRs();
        if (rs != null) {
            Coneccion co = new Coneccion();
            try {
                String sq = "";
                int codi = 0;
                String fecHor = "";
                co.update("TRUNCATE sector RESTART IDENTITY");
                while (rs.next()) {
                    
                     sql = "INSERT INTO sector(sec_descri) values('"+rs.getString(1)+"')";
                    

                    co.update(sql);
                    //System.out.println(producto.toString());
                    canti++;
                }
                JOptionPane.showMessageDialog(null, canti + " Rubros Importados");
                co.close();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
        con.close();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
         int canti = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        String sql = "";
        sql = "Select IdeClie,RazClie,RucClie,DirClie,TelClie from cliente";
        con_acces con = new con_acces();
        con.consulta(sql);
        ResultSet rs = null;
        rs = con.getRs();
        if (rs != null) {
            Coneccion co = new Coneccion();
            try {
                String sq = "";
                int codi = 0;
                String fecHor = "";
                co.update("TRUNCATE clientes RESTART IDENTITY");
                PreparedStatement pSta;
                while (rs.next()) {
                    
                    Clientes cli = new Clientes();

                    cli.setCli_nombre(rs.getString("RazClie"));
                    //cli.setCli_ci(Integer.parseInt(txCI.getText()));
                    cli.setCli_ruc(rs.getString("RucClie"));
                    cli.setCli_direc(rs.getString("DirClie"));
                    cli.setCli_tel(rs.getString("TelClie"));
                    
            sql = "Insert into clientes(cli_nombre,cli_tel,cli_direc,cli_ruc ) "
                    + "values(?,?,?,?)";
            pSta = co.getCon().prepareStatement(sql);
       
            pSta.setString(1, cli.getCli_nombre());
            pSta.setString(2, cli.getCli_tel());
            pSta.setString(3, cli.getCli_direc());
            pSta.setString(4, cli.getCli_ruc());
                    

                    pSta.executeUpdate();
                    //System.out.println(producto.toString());
                    canti++;
                }
                JOptionPane.showMessageDialog(null, canti + " Clientes Importados");
                co.close();
            } catch (SQLException ex) {
                System.out.println(ex.getMessage());
            }
        }
        con.close();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
           int canti = 0;
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");

        ResultSet rs = null;

            Coneccion co = new Coneccion();
            String sq = "";
            co.update("update productos set pro_unidad = 0 where pro_unidad=1");
            co.update("update productos set pro_unidad = 1 where pro_unidad=2");
            JOptionPane.showMessageDialog(null, canti + " Unidad actualizada");
            co.close();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TranspasoAcces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TranspasoAcces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TranspasoAcces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TranspasoAcces.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TranspasoAcces().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    // End of variables declaration//GEN-END:variables
}
