/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Connection.Coneccion;
import Entity.Clientes;
import Entity.Mesa;
import Entity.RenderCelda;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import java.util.List;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;

/**
 *
 * @author mac
 */
public class ver_mesass extends javax.swing.JDialog {

    /**
     * Creates new form ver_mesass
     */
    
    List<Mesa> mesas=null;
    Mesa mesa = new Mesa();
    
    DefaultTableModel modelo;
    public ver_mesass(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        lisMesas();
    }
    
    
    private void lisMesas(){
        Coneccion con = new Coneccion();
        
        try{
           con.setRs(con.getStmt().executeQuery("Select * from mesa order by m_codigo")); 
           
           while(con.getRs().next()){
               Mesa mesa = new Mesa();
               mesa.setM_codigo(con.getRs().getInt("m_codigo"));
               mesa.setM_descri(con.getRs().getString("m_descri"));
               mesa.setM_estado(con.getRs().getBoolean("m_estatus"));
               
               if(mesas == null)mesas = new ArrayList<>();
               
               mesas.add(mesa);
           }
           
           modelo = (DefaultTableModel) jTMesas.getModel();
           modelo.setRowCount(0);
           this.jTMesas.setModel(modelo);
           
           if(mesas != null && !mesas.isEmpty()){
              /* for(Mesa m:mesas){
                Object[] mesa = new Object[modelo.getColumnCount()];
                mesa[0] = m.getM_descri();
                
                modelo.addRow(mesa);
               }*/
               
               for(int i=0;i<mesas.size();i=i+4){
                Object[] mesa = new Object[modelo.getColumnCount()];
                mesa[0] = mesas.get(i+0).getM_descri();
                mesa[1] = mesas.get(i+1).getM_descri();
                mesa[2] = mesas.get(i+2).getM_descri();
                mesa[3] = mesas.get(i+3).getM_descri();
                
                modelo.addRow(mesa);
               }
           }
           
           TableCellRenderer renderer = new RenderCelda();
    
           jTMesas.setDefaultRenderer( Object.class, renderer );
           
           jTMesas.getTableHeader().setUI(null);
           
        }catch(Exception e){
            System.out.println("frames.ver_mesass.lisMesas()"+e.getMessage());
        }
    }
    
    public void editar() {

        int filasele = jTMesas.getSelectedRow();
        int ColumSele = jTMesas.getSelectedColumn();

        String sMes = String.valueOf(jTMesas.getValueAt(filasele, ColumSele).toString());

        for (Mesa m : mesas) {
            this.mesa = m;
            if (m.getM_descri().equalsIgnoreCase(sMes)) {
                break;
            }
        }

        this.dispose();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTMesas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Mesas");

        jTMesas.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTMesas.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jTMesas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1", "2", "3", "4"},
                {"11", "12", "13", "14"},
                {"21", "22", "23", "24"}
            },
            new String [] {
                "Título 1", "Título 2", "Título 3", "Título 4"
            }
        ));
        jTMesas.setCellSelectionEnabled(false);
        jTMesas.setGridColor(new java.awt.Color(0, 0, 0));
        jTMesas.setIntercellSpacing(new java.awt.Dimension(4, 4));
        jTMesas.setMinimumSize(new java.awt.Dimension(180, 180));
        jTMesas.setPreferredSize(new java.awt.Dimension(300, 300));
        jTMesas.setRowHeight(100);
        jTMesas.setShowGrid(false);
        jTMesas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTMesasMouseClicked(evt);
            }
        });
        jTMesas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTMesasKeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTMesas);
        jTMesas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        setSize(new java.awt.Dimension(674, 385));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTMesasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTMesasKeyPressed
         if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            editar();
        }
    }//GEN-LAST:event_jTMesasKeyPressed

    private void jTMesasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTMesasMouseClicked
        editar();
    }//GEN-LAST:event_jTMesasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ver_mesass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ver_mesass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ver_mesass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ver_mesass.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ver_mesass dialog = new ver_mesass(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTMesas;
    // End of variables declaration//GEN-END:variables
}
