/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import Connection.Coneccion;
import Entity.Clientes;
import Entity.ItemVen;
import Entity.Numero_a_Letra;
import Entity.Venta;
import Entity.deucli;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DecimalFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author WIN7
 */
public class ver_total_rest extends javax.swing.JDialog {

    /**
     * Creates new form ver_total
     */
    DecimalFormat df = new DecimalFormat("###,###,###.##");
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    Calendar Cfecha = new GregorianCalendar();
    Coneccion coneccion;
    Connection con;
    String fecha = "";
    public Venta venta;
    public int numven, tipfac, situ;
    private Clientes clie;
    double dol = 0.0, rea = 0.0, pes = 0.0;
    public deucli deu;

    public Venta getVenta() {
        return venta;
    }

    public void setVenta(Venta venta) {
        this.venta = venta;
    }

    public int getNumven() {
        return numven;
    }

    public void setNumven(int numven) {
        this.numven = numven;
    }

    public int getTipfac() {
        return tipfac;
    }

    public void setTipfac(int tipfac) {
        this.tipfac = tipfac;
    }

    public deucli getDeu() {
        return deu;
    }

    public void setDeu(deucli deu) {
        this.deu = deu;
    }

    public ver_total_rest(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    public int getSitu() {
        return situ;
    }

    public void setSitu(int situ) {
        this.situ = situ;
    }

    private void cargar() {

        this.txTotal.setText(df.format(getVenta().getVen_total()));
        txCodcli.setText(getVenta().getVen_cliente().toString());
        consultarCliente();
        consultarMoneda();
        txEntrega.grabFocus();

    }

    public void consultarCliente() {
        String sql;

        sql = "select cli_codigo,cli_nombre,cli_ruc from "
                + "clientes  "
                + "  where cli_codigo =" + txCodcli.getText() + "   order by cli_codigo";

        Coneccion con = new Coneccion();
        ResultSet rs;
        Clientes cli = null;

        try {
            con.consulta(sql);
            rs = con.getRs();
            if (rs.next()) {
                txdescli.setText(rs.getString("cli_nombre"));
                txRUC.setText(rs.getString("cli_ruc"));
            }

            con.close();
        } catch (Exception e) {
            if (con != null) {
                con.close();
            }
        }
    }

    public void consultarMoneda() {
        String sql;
        sql = "select mon_codigo,mon_dolar,mon_pes,mon_real,mon_fecha from moneda";
        Coneccion con = new Coneccion();
        ResultSet rs;
        try {
            con.consulta(sql);
            rs = con.getRs();
            if (rs.next()) {
                dol = rs.getDouble("mon_dolar");
                rea = rs.getDouble("mon_real");
                pes = rs.getDouble("mon_pes");
            }

            con.close();
        } catch (Exception e) {
            if (con != null) {
                con.close();
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tipFac = new javax.swing.ButtonGroup();
        jPanel2 = new javax.swing.JPanel();
        btAcepta = new javax.swing.JButton();
        txEntrega = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txRUC = new javax.swing.JTextField();
        txVuelto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jRComun = new javax.swing.JRadioButton();
        jRLega = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txCodcli = new javax.swing.JTextField();
        txTotal = new javax.swing.JTextField();
        txdescli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btCancel = new javax.swing.JButton();
        txDolar = new javax.swing.JTextField();
        txReal = new javax.swing.JTextField();
        txPeso = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txVreal = new javax.swing.JTextField();
        txVdolar = new javax.swing.JTextField();
        txVpeso = new javax.swing.JTextField();
        txEdol = new javax.swing.JTextField();
        txEpes = new javax.swing.JTextField();
        txEreal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Finalizar Pago");
        setBackground(new java.awt.Color(255, 255, 204));
        setUndecorated(true);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(235, 248, 193));

        btAcepta.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btAcepta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ico_aceptar.png"))); // NOI18N
        btAcepta.setMnemonic('A');
        btAcepta.setText("Aceptar");
        btAcepta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAceptaActionPerformed(evt);
            }
        });
        btAcepta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btAceptaKeyPressed(evt);
            }
        });

        txEntrega.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        txEntrega.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txEntregaFocusGained(evt);
            }
        });
        txEntrega.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txEntregaActionPerformed(evt);
            }
        });
        txEntrega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txEntregaKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txEntregaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txEntregaKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("R.U.C.:");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel7.setText("FINALIZAR PAGO");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Vuelto:");

        txRUC.setEditable(false);
        txRUC.setFocusable(false);

        txVuelto.setEditable(false);
        txVuelto.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        txVuelto.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txVuelto.setFocusable(false);
        txVuelto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txVueltoFocusGained(evt);
            }
        });
        txVuelto.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txVueltoInputMethodTextChanged(evt);
            }
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
        });
        txVuelto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txVueltoActionPerformed(evt);
            }
        });
        txVuelto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txVueltoKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Tipo de Comprobante");

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));
        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        tipFac.add(jRComun);
        jRComun.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jRComun.setSelected(true);
        jRComun.setText("Común");
        jRComun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRComunKeyPressed(evt);
            }
        });

        tipFac.add(jRLega);
        jRLega.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jRLega.setText("Legal");
        jRLega.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jRLegaItemStateChanged(evt);
            }
        });
        jRLega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jRLegaKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addComponent(jRComun)
                .addGap(39, 39, 39)
                .addComponent(jRLega)
                .addContainerGap(105, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRComun)
                    .addComponent(jRLega))
                .addContainerGap())
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("F4-Cliente:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Total Venta:");

        txCodcli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txCodcli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txCodcliActionPerformed(evt);
            }
        });
        txCodcli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCodcliKeyPressed(evt);
            }
        });

        txTotal.setEditable(false);
        txTotal.setBackground(new java.awt.Color(0, 102, 0));
        txTotal.setFont(new java.awt.Font("Tahoma", 1, 40)); // NOI18N
        txTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txTotal.setFocusable(false);
        txTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txTotalActionPerformed(evt);
            }
        });

        txdescli.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txdescli.setEnabled(false);
        txdescli.setFocusable(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Efectivo:");

        btCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/ico_cancel.png"))); // NOI18N
        btCancel.setMnemonic('C');
        btCancel.setText("Cancelar");
        btCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelActionPerformed(evt);
            }
        });

        txDolar.setEditable(false);
        txDolar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txDolar.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txDolar.setEnabled(false);

        txReal.setEditable(false);
        txReal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txReal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txReal.setEnabled(false);

        txPeso.setEditable(false);
        txPeso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txPeso.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txPeso.setEnabled(false);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/dolar.png"))); // NOI18N
        jLabel9.setPreferredSize(new java.awt.Dimension(44, 23));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/peso.png"))); // NOI18N
        jLabel10.setPreferredSize(new java.awt.Dimension(43, 23));

        txVreal.setEditable(false);
        txVreal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txVreal.setFocusable(false);

        txVdolar.setEditable(false);
        txVdolar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txVdolar.setFocusable(false);

        txVpeso.setEditable(false);
        txVpeso.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txVpeso.setFocusable(false);

        txEdol.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txEdol.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txEdolKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txEdolKeyTyped(evt);
            }
        });

        txEpes.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txEpes.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txEpesKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txEpesKeyTyped(evt);
            }
        });

        txEreal.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txEreal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txErealKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txErealKeyTyped(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/real.png"))); // NOI18N
        jLabel11.setPreferredSize(new java.awt.Dimension(43, 23));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel8.setText("DOLAR");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel12.setText("REAL");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel13.setText("PESO ARGENTINO");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel6))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txCodcli, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txdescli))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txRUC, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(0, 0, Short.MAX_VALUE)))))
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(txDolar, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                            .addComponent(txVdolar))
                                        .addGap(32, 32, 32))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(44, 44, 44)))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(txReal, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(27, 27, 27))
                                            .addGroup(jPanel2Layout.createSequentialGroup()
                                                .addComponent(txVreal, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(31, 31, 31)))
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txVpeso, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(13, 13, 13))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel12))
                                        .addGap(47, 47, 47)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel13)))))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(btAcepta, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(60, 60, 60)
                                        .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(102, 102, 102)))
                                .addGap(5, 5, 5))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel3))))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txEdol, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(txEreal, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txEpes, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(2, 2, 2)))
                .addGap(32, 32, 32))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel7)
                .addGap(2, 2, 2)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txDolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txEntrega, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txEdol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txEpes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txEreal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txVuelto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txVreal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txVdolar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txVpeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(3, 3, 3)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txCodcli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txdescli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txRUC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAcepta, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(480, 586));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txEntregaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txEntregaKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != '.')) {
            evt.consume();
        }


    }//GEN-LAST:event_txEntregaKeyTyped

    private void txVueltoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txVueltoFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txVueltoFocusGained

    private void txVueltoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txVueltoKeyReleased

    }//GEN-LAST:event_txVueltoKeyReleased

    private void txVueltoInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txVueltoInputMethodTextChanged

    }//GEN-LAST:event_txVueltoInputMethodTextChanged

    private void txEntregaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txEntregaKeyReleased
        try {
            if (!txEntrega.getText().isEmpty()) {
                txEntrega.setText(df.format(df.parse(txEntrega.getText())));

                double res = df.parse(txEntrega.getText()).doubleValue() - df.parse(txTotal.getText()).doubleValue();
                txVuelto.setText(df.format(res));

                double rd = res / dol;
                txVdolar.setText(df.format(rd));
                double rr = res / rea;
                txVreal.setText(df.format(rr));
                double rp = res / pes;
                txVpeso.setText(df.format(rp));
            }
        } catch (ParseException ex) {
            Logger.getLogger(ver_total_rest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txEntregaKeyReleased

    private void txEntregaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txEntregaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txEntregaActionPerformed

    private void txEntregaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txEntregaFocusGained
        try {

            cargar();

            if (!txTotal.getText().isEmpty()) {
                txTotal.setText(df.format(df.parse(txTotal.getText())));
                double td = df.parse(txTotal.getText()).doubleValue() / dol;
                txDolar.setText(df.format(td));

                double tr = df.parse(txTotal.getText()).doubleValue() / rea;
                txReal.setText(df.format(tr));

                double tp = df.parse(txTotal.getText()).doubleValue() / pes;
                txPeso.setText(df.format(tp));
            }
        } catch (ParseException ex) {
            Logger.getLogger(ver_total_rest.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_txEntregaFocusGained

    private void jRLegaItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jRLegaItemStateChanged
        if (jRLega.isSelected()) {
            txCodcli.setEditable(true);
            txCodcli.grabFocus();
        }
    }//GEN-LAST:event_jRLegaItemStateChanged

    private void btAceptaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAceptaActionPerformed
        if (jRLega.isSelected()) {
            if (Integer.parseInt(txCodcli.getText()) > 0 && !txdescli.getText().isEmpty()) {
                GuaVenta();
            } else {
                JOptionPane.showMessageDialog(null, "Seleccionar cliente válido");
                txCodcli.grabFocus();
            }

        } else {
            GuaVenta();
        }
    }//GEN-LAST:event_btAceptaActionPerformed

    private void txCodcliKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCodcliKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_F4) {
            ver_Cliente vcli = new ver_Cliente(null, true);
            vcli.setVisible(true);
            clie = vcli.vClie;

            txCodcli.setText(clie.getCli_codigo().toString());
            txdescli.setText(clie.getCli_nombre().trim());
            txRUC.setText(clie.getCli_ruc());
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                if (!txCodcli.getText().isEmpty()) {
                    consultarCliente();
                } else {
                    txCodcli.setText("0");
                    txdescli.setText("Cliente ocasional");
                }
            }
        }
    }//GEN-LAST:event_txCodcliKeyPressed

    private void txEntregaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txEntregaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jRComun.grabFocus();
        }
    }//GEN-LAST:event_txEntregaKeyPressed

    private void txVueltoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txVueltoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txVueltoActionPerformed

    private void jRLegaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRLegaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.jRLega.setSelected(true);
        }
    }//GEN-LAST:event_jRLegaKeyPressed

    private void jRComunKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jRComunKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.btAcepta.requestFocus();
        }
    }//GEN-LAST:event_jRComunKeyPressed

    private void btAceptaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btAceptaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.btAcepta.doClick();
        }
    }//GEN-LAST:event_btAceptaKeyPressed

    private void txCodcliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txCodcliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txCodcliActionPerformed

    private void btCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelActionPerformed
        int op = JOptionPane.showOptionDialog(null,
                "ATENCIÓN",
                "Esta seguro/a de cancelar el pago",
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE,
                null, // null para icono por defecto.
                null, // null para YES, NO y CANCEL
                null);
        if (op == 0) {
            setSitu(2);
            this.dispose();
        }
    }//GEN-LAST:event_btCancelActionPerformed

    private void txTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txTotalActionPerformed

    private void txEdolKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txEdolKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                double ed = df.parse(txEdol.getText()).doubleValue() * dol;
                txEntrega.setText(df.format(ed));

                if (!txEntrega.getText().isEmpty()) {
                    txEntrega.setText(df.format(df.parse(txEntrega.getText())));

                    double res = df.parse(txEntrega.getText()).doubleValue() - df.parse(txTotal.getText()).doubleValue();
                    txVuelto.setText(df.format(res));

                    double rd = res / dol;
                    txVdolar.setText(df.format(rd));
                    double rr = res / rea;
                    txVreal.setText(df.format(rr));
                    double rp = res / pes;
                    txVpeso.setText(df.format(rp));

                    jRComun.grabFocus();
                }

            } catch (ParseException ex) {
                Logger.getLogger(ver_total_rest.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txEdolKeyPressed

    private void txEdolKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txEdolKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txEdolKeyTyped

    private void txErealKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txErealKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txErealKeyTyped

    private void txEpesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txEpesKeyTyped
        char c = evt.getKeyChar();
        if (((c < '0') || (c > '9')) && (c != '.')) {
            evt.consume();
        }
    }//GEN-LAST:event_txEpesKeyTyped

    private void txErealKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txErealKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                double er = df.parse(txEreal.getText()).doubleValue() * rea;
                txEntrega.setText(df.format(er));

                if (!txEntrega.getText().isEmpty()) {
                    txEntrega.setText(df.format(df.parse(txEntrega.getText())));

                    double res = df.parse(txEntrega.getText()).doubleValue() - df.parse(txTotal.getText()).doubleValue();
                    txVuelto.setText(df.format(res));

                    double rd = res / dol;
                    txVdolar.setText(df.format(rd));
                    double rr = res / rea;
                    txVreal.setText(df.format(rr));
                    double rp = res / pes;
                    txVpeso.setText(df.format(rp));
                    jRComun.grabFocus();
                }

            } catch (ParseException ex) {
                Logger.getLogger(ver_total_rest.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txErealKeyPressed

    private void txEpesKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txEpesKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            try {
                double ep = df.parse(txEpes.getText()).doubleValue() * pes;
                txEntrega.setText(df.format(ep));

                if (!txEntrega.getText().isEmpty()) {
                    txEntrega.setText(df.format(df.parse(txEntrega.getText())));

                    double res = df.parse(txEntrega.getText()).doubleValue() - df.parse(txTotal.getText()).doubleValue();
                    txVuelto.setText(df.format(res));

                    double rd = res / dol;
                    txVdolar.setText(df.format(rd));
                    double rr = res / rea;
                    txVreal.setText(df.format(rr));
                    double rp = res / pes;
                    txVpeso.setText(df.format(rp));
                    jRComun.grabFocus();
                }

            } catch (ParseException ex) {
                Logger.getLogger(ver_total_rest.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_txEpesKeyPressed

    private void GuaVenta() {
        int tipven;
        try {

            ResultSet rs;
            int codvent = 0;

            String Hora = new SimpleDateFormat("HH:mm:ss").format(Calendar.getInstance().getTime());
            Cfecha = Calendar.getInstance();
            fecha = sdf.format(Cfecha.getTime());

            Venta ven = getVenta();
            ven.setVen_cliente(Integer.parseInt(txCodcli.getText()));

            Numero_a_Letra nl = new Numero_a_Letra();
            DecimalFormat format = new DecimalFormat("#.##");
            //System.out.println("Letra " + nl.Convertir(format.format(ven.getVen_total()), true));
            ven.setVen_totlet(nl.Convertir(format.format(ven.getVen_total()), true));

            coneccion = new Coneccion();
            con = coneccion.getCon();
            Statement stmt;

            con.setAutoCommit(false);
            stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
            int numfac = 0;
            String sql;
            if (jRComun.isSelected()) {
                this.setTipfac(1);
                try {
                    if (txEntrega.getText().isEmpty()) {
                        ven.setVen_efectivo(0.0);
                        ven.setVen_vuelto(0.0);
                    } else {
                        ven.setVen_efectivo(df.parse(txEntrega.getText()).doubleValue());
                        ven.setVen_vuelto(df.parse(txVuelto.getText()).doubleValue());
                    }
                } catch (ParseException ex) {
                    Logger.getLogger(ver_total_rest.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                this.setTipfac(2);
                sql = "select (emp_numfac3+1) as numfac,(to_char(emp_numfac1, 'FM999099')||'-'||to_char(emp_numfac2, 'FM999099')||'-'||to_char((emp_numfac3+1), 'FM9990999999')) AS des_numfac from empresa";
                rs = stmt.executeQuery(sql);

                if (rs.next()) {
                    numfac = rs.getInt("numfac");
                    ven.setNunfac(rs.getString("des_numfac"));
                    try {
                        if (txEntrega.getText().isEmpty()) {
                            ven.setVen_efectivo(0.0);
                            ven.setVen_vuelto(0.0);
                        } else {
                            ven.setVen_efectivo(df.parse(txEntrega.getText()).doubleValue());
                            ven.setVen_vuelto(df.parse(txVuelto.getText()).doubleValue());
                        }
                    } catch (ParseException ex) {
                        Logger.getLogger(ver_total_rest.class.getName()).log(Level.SEVERE, null, ex);
                    }

                }
                stmt.executeUpdate("update empresa set emp_numfac3=" + numfac);
            }
            
            ven.setVen_estado(true);
            
             setNumven(ven.getVen_codigo());
            
            sql = "Update ventas set ven_fecha = '" + ven.getVen_fecha() + "', "
                    + "ven_hora = '" + ven.getVen_hora() + "', "
                    + "ven_codven = " + ven.getVen_codven() + ", "
                    + "ven_total = " + ven.getVen_total() + ", "
                    + "ven_cliente = " + ven.getVen_cliente() + ", "
                    + "ven_tipo= " + ven.getTipven() + ","
                    + "ven_numfac= '" + ven.getNunfac() + "', "
                    + "ven_efectivo= " + ven.getVen_efectivo() + ","
                    + "ven_vuelto= " + ven.getVen_vuelto() + ", "
                    + "ven_descuento= " + ven.getVen_descuento() + ", "
                    + "ven_totlet= '" + ven.getVen_totlet() + "' ,"
                    + "ven_estado= " + ven.isVen_estado() + " "
                    + "where ven_codigo =" + ven.getVen_codigo();

            stmt.executeUpdate(sql);
            
            stmt.executeUpdate("update mesa set m_estatus= " + 1
                        + "where m_codigo=" + ven.getVen_mesa());

            con.commit();
            con.close();
            setSitu(1);
            this.dispose();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error al registrar Ventas " + e.getMessage());
            //System.out.println(e.getMessage());
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ver_total_rest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ver_total_rest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ver_total_rest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ver_total_rest.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ver_total_rest dialog = new ver_total_rest(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcepta;
    private javax.swing.JButton btCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRComun;
    private javax.swing.JRadioButton jRLega;
    private javax.swing.ButtonGroup tipFac;
    private javax.swing.JTextField txCodcli;
    private javax.swing.JTextField txDolar;
    private javax.swing.JTextField txEdol;
    private javax.swing.JTextField txEntrega;
    private javax.swing.JTextField txEpes;
    private javax.swing.JTextField txEreal;
    private javax.swing.JTextField txPeso;
    private javax.swing.JTextField txRUC;
    private javax.swing.JTextField txReal;
    private javax.swing.JTextField txTotal;
    private javax.swing.JTextField txVdolar;
    private javax.swing.JTextField txVpeso;
    private javax.swing.JTextField txVreal;
    private javax.swing.JTextField txVuelto;
    private javax.swing.JTextField txdescli;
    // End of variables declaration//GEN-END:variables
}
