/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frames;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import Connection.Coneccion;
import Entity.Usuario;
import java.awt.event.KeyEvent;

/**
 *
 * @author HP
 */
public class reg_usuario extends javax.swing.JInternalFrame {

    int tipo = 0;
    Usuario usu = new Usuario();

    public reg_usuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txUser = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txNombre = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jbCancel = new javax.swing.JButton();
        txPass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        cbNivel = new javax.swing.JComboBox();

        setClosable(true);
        setIconifiable(true);
        setTitle("Registrar Usuario");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Usuario:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        txCodigo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        txCodigo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txCodigoFocusLost(evt);
            }
        });
        txCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txCodigoKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txCodigoKeyTyped(evt);
            }
        });
        jPanel1.add(txCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 80, -1));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Código:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        txUser.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 380, -1));

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Nombre:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));

        txNombre.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPanel1.add(txNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 380, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Nivel:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 480, -1));

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Eliminar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, -1, -1));

        jbCancel.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jbCancel.setText("Cancelar");
        jbCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jbCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));
        jPanel1.add(txPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 380, -1));

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Contraseña:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        cbNivel.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        cbNivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Administrador", "Operador" }));
        jPanel1.add(cbNivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 200, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 480, 300));

        setBounds(0, 0, 520, 394);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String sql = "";
        ResultSet rs = null;
        Coneccion con = new Coneccion();
        int niv = cbNivel.getSelectedIndex() + 1;

        try {
            if (tipo == 0) {
                sql = "insert into acceso(acc_nombre,acc_user,acc_pass,acc_nivel) values('" + txNombre.getText()
                        + "','" + txUser.getText() + "','" + txPass.getText().toString() + "'," + niv + ")";
            } else {
                sql = "update acceso set acc_nombre ='" + txNombre.getText()
                        + "',acc_user='" + txUser.getText()
                        + "',acc_pass='" + txPass.getText().toString()
                        + "',acc_nivel=" + niv + " where acc_id=" + txCodigo.getText().trim();
            }

            int r = con.update(sql);
            if (r == 1) {
                JOptionPane.showMessageDialog(null, "Guardado con éxito");
                jbCancel.doClick();
            }

        } catch (Exception e) {
            System.out.println("error " + e.getMessage());
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (!txCodigo.getText().isEmpty()) {
            String sql = "";
            ResultSet rs = null;
            Coneccion con = new Coneccion();
            int niv = cbNivel.getSelectedIndex() + 1;

            try {
                
                    sql = "update acceso set acc_situ = 0 where acc_id=" + txCodigo.getText().trim();
                

                int r = con.update(sql);
                if (r == 1) {
                    JOptionPane.showMessageDialog(null, "Eliminado con éxito");
                    jbCancel.doClick();
                }

            } catch (Exception e) {
                System.out.println("error " + e.getMessage());
            }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jbCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelActionPerformed
        txCodigo.setText("");
        txNombre.setText("");
        txUser.setText("");
        txPass.setText("");
        cbNivel.setSelectedIndex(0);
        txCodigo.grabFocus();
    }//GEN-LAST:event_jbCancelActionPerformed

    private void txCodigoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txCodigoFocusLost
        consultarUsu();
    }//GEN-LAST:event_txCodigoFocusLost

    private void txCodigoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCodigoKeyTyped
      char caracter = evt.getKeyChar();

        // Verificar si la tecla pulsada no es un digito
        if (((caracter < '0')
                || (caracter > '9'))
                && (caracter != '\b' /*corresponde a BACK_SPACE*/)) {
            evt.consume();  // ignorar el evento de teclado
        }
    }//GEN-LAST:event_txCodigoKeyTyped

    private void txCodigoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txCodigoKeyPressed
       if (evt.getKeyCode() == KeyEvent.VK_F4) {
            ver_usuarios vusu = new ver_usuarios(null, true);

            vusu.setVisible(true);
            usu = vusu.vUsu;
            txCodigo.setText(usu.getAcc_id().toString());
            
        } else {
            if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
                ver_usuarios vusu = new ver_usuarios(null, true);

            vusu.setVisible(true);
            usu = vusu.vUsu;
            txCodigo.setText(usu.getAcc_id().toString());
            }
        }
    }//GEN-LAST:event_txCodigoKeyPressed

    public void consultarUsu() {
        String sql = "";
        tipo = 0;
        ResultSet rs = null;
        Coneccion con = new Coneccion();

        if (!txCodigo.getText().isEmpty()) {

            sql = "select  acc_nombre,acc_user,acc_pass,acc_nivel,acc_situ  from acceso "
                    + "where acc_situ = 1 and  acc_id = " + txCodigo.getText().trim();

            con.consulta(sql);
            rs=con.getRs();
        }

        if (rs != null) {
            tipo = 1;
            try {
                while (rs.next()) {

                    txNombre.setText(rs.getString("acc_nombre"));
                    txUser.setText(rs.getString("acc_user"));
                    txPass.setText(rs.getString("acc_pass"));
                    if (rs.getInt("acc_nivel") == 1) {
                        cbNivel.setSelectedIndex(0);
                    } else {
                        cbNivel.setSelectedIndex(1);
                    }

                }
            } catch (SQLException ex) {
                System.out.println("Error " + ex.getMessage());
            }
            rs = null;
        } else {
tipo=0;
        }

        con.close();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbNivel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbCancel;
    private javax.swing.JTextField txCodigo;
    private javax.swing.JTextField txNombre;
    private javax.swing.JPasswordField txPass;
    private javax.swing.JTextField txUser;
    // End of variables declaration//GEN-END:variables
}
